### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by amweiss** [tomoyukim/vscode-mermaid-editor#10]
The mermaid live editor is using the monaco library and contains a definition for the mermaid language: https://github.com/mermaid-js/mermaid-live-editor/tree/master/src/mermaid-language

Since it's based on the same editor engine, is it possible to incorporate this for syntax highlighting?

**Comment by tomoyukim** [comment]
Hello. Thank you for really great request and information around monaco-editor. AFAIK, Monarch is not supported in VS so far. (https://github.com/microsoft/vscode/issues/216) But I'll try to support syntax highlighting.

**Comment by tomoyukim** [comment]
Thank you for waiting the feature. v0.8.0 has supported the syntax highlight.
