### ISSUE TITLE
Image generation doesn't work for formats other than SVG

### ISSUE THREAD

**Issue by oscarrobinson** [tomoyukim/vscode-mermaid-editor#12]
When I change the generated image format to `png`, `jpg` or `webp`, nothing happens when using the generate image command. The file generates fine when the format is `svg`.

Love the plugin btw 😄

**Comment by apkrieg** [comment]
I'm having the same issue. I'm trying to generate a PNG.

**Comment by apkrieg** [comment]
A little more information. Generating the other image type does work for the following:
```
graph LR;
    A-->B
```

But not this:
```
graph LR;
    A["a<br>b"]-->B
```

It seems when there is HTML included in the text it errors out. I'm not sure if this is the only scenario, but it is the one I am experiencing.

**Comment by tomoyukim** [comment]
Thank you for reporting the bug. I could reproduce the case mentioned by @apkrieg. Let me investigate and I'm sorry for your inconvenient.

**Comment by tomoyukim** [comment]
I found the bug coming from mermaid.js (https://github.com/mermaid-js/mermaid/issues/1504). If `<br>` tag is contained in a `graph` diagram, a generated `<svg>` tag has `<br>` tag in it. Then, it causes loading error in `Image` object of canvas.

**Comment by tomoyukim** [comment]
I released v0.7.0 with a patch for this symptom. I believe you can avoid the error in case that there's `<br>` tag in `graph` diagram by this change. If you have any other case you face to trouble to generate image, please let me know. Thank you for your cooperation.

**Comment by tomoyukim** [comment]
I could resolve this symptom in v0.8.1.
