### ISSUE TITLE
Dynamic Exported Image Size

### ISSUE THREAD

**Issue by cyrusdaboo** [tomoyukim/vscode-mermaid-editor#17]
Right now the exported image size is set via `mermaid-editor.generate.width` and `mermaid-editor.generate.height` settings. But that is global to all mermaid documents. Small diagrams typically end up as small images in the top-left corner of the PNG.

Can you please add some form of dynamic sizing of the exported images? Ideally this would involve a simple scale-factor setting that, when set to 1, would render text as the correct font size. Exporting would then automatically calculate the bounds of the image based on that scale (perhaps we also need a dpi setting for image rendering).

**Comment by tomoyukim** [comment]
I introduced a new config `mermaid-editor.generate.scale` instead of width and height in v0.11.0. Please check it out!
