### ISSUE TITLE
Line break with <br> does not work

### ISSUE THREAD

**Issue by wenlzhang** [tomoyukim/vscode-mermaid-editor#21]
With the Mermaid live editor, it works. However, with this plugin, it does not work. When searching within the issues, it should work in version 0.8.1?

**Comment by tomoyukim** [comment]
Yes, I fixed the generation error in the plugin by handling svg element correctly rendered by mermaid.js internally. As the result of this change, the plugin can work as expected in mermaid.js originally.

**Comment by wenlzhang** [comment]
Sorry about the confusion... I realize that I missed "not" in the issue title. I was meant to say that with the latest version of this VS Code plugin, line break with `<br>` does not work for me. `<br>` displays as it is.

**Comment by tomoyukim** [comment]
Thank you for waiting. This should be resolved in v0.9.0.
