### ISSUE TITLE
Output tab auto open

### ISSUE THREAD

**Issue by jsbrain** [tomoyukim/vscode-mermaid-editor#22]
Hi,

when I edit a file and there's an error, the output tab showing the error will automatically be opened on every keystroke.

I'm pretty sure this is caused by this plugin, as I normally don't see that behavior in any other circumstances.
For me, that's pretty annoying and that's probably not intended anyways so that should either be fixed or configurable I guess? :)

**Comment by ascarter** [comment]
I'd prefer the output only on save. Showing while typing is distracting.

**Comment by tomoyukim** [comment]
Thank you for waiting! I've improved this behavior on v0.10.0. Let me know if you have any trouble.
