### ISSUE TITLE
How to set configs?

### ISSUE THREAD

**Issue by alexandregomes-acceptto** [tomoyukim/vscode-mermaid-editor#23]
Hi, I'm having some trouble setting up configs. All I was trying is to setup the output path for images, and change the type to png, but I can't seem to figure out the correct place/syntax.

diagram.mmd
```
sequenceDiagram
%% @config{./mmd.json}
    Alice->>John: Hello John, how are you?
```

mmd.json
```
{
  "theme": "default",
  "type": "png",
  "mermaid-editor": {
    "generate": {
      "type": "png",
      "outputPath": "./images/"
    }
  },
  "outputPath": "./images/"
}

```

**Comment by tomoyukim** [comment]
Sorry to confuse. `%% @config{./mmd.json}` attribute only for mermaid config. The output path or image type of generation are extension settings. I believe you can find the properties in your extension config. Try open extension config and search "mermaid".

**Comment by alexandregomes-acceptto** [comment]
Thanks for the explanation. This makes things a bit harder to reproduce though, every developer on a team would have to know to add those configs.
