### ISSUE TITLE
Fontsize (CSS-Style sheet?)

### ISSUE THREAD

**Issue by incoggnito** [tomoyukim/vscode-mermaid-editor#25]
I would like to increase the fontsize, and i'm new to mermaid...
Is it possible to include a css-style sheet?

**Comment by tomoyukim** [comment]
It seems you can change `fontSize` by setting the config for theme AFAIK. I'm sorry for late reply.
https://mermaid-js.github.io/mermaid/#/theming?id=theme-variables-reference-table
