### ISSUE TITLE
Some arrow and line types doesn't seem to work

### ISSUE THREAD

**Issue by KLIII** [tomoyukim/vscode-mermaid-editor#29]
I'm on v0.8.1, and I'm having trouble with just a few of the arrow and line types in flowcharts:
![image](https://user-images.githubusercontent.com/22798719/102446484-e1a59b00-3ffb-11eb-95ad-ee634d027369.png)

**Comment by tomoyukim** [comment]
Thank you for waiting. This should be resolved in v0.9.0.
