### ISSUE TITLE
Configure relative path to mmd file

### ISSUE THREAD

**Issue by rkristelijn** [tomoyukim/vscode-mermaid-editor#3]
It would be great to be able to configure the settings to generate the png or svg image to be generated in the same path as the mmd file

**Comment by tomoyukim** [comment]
Thank you for your feedback. I'll try to update.

**Comment by tomoyukim** [comment]
I believe latest version can support same path as mmd file. Please check v0.4.3 out. Thank you.

**Comment by rkristelijn** [comment]
@tomoyukim > thank you, tested and works! Great start of the week, have a good one! :D
