### ISSUE TITLE
Cannot use <<interface>>, <<abstract>>, and virtual member (*) for classDiagram

### ISSUE THREAD

**Issue by KLIII** [tomoyukim/vscode-mermaid-editor#30]
E.g., the following works in mermaid live editor, but not when I used it in the plugin. Having the `<<interface>>` would prevent the whole diagram from rendering. If I remove that, the `*` for marking a method virtual still has no effect in the plugin.
![image](https://user-images.githubusercontent.com/22798719/103022184-7850eb00-4519-11eb-8147-5a1ba6d7bf62.png)

**Comment by tomoyukim** [comment]
Thank you for waiting. This should be resolved in v0.9.0.
