### ISSUE TITLE
V0.9.0 fails to generate preview

### ISSUE THREAD

**Issue by KLIII** [tomoyukim/vscode-mermaid-editor#31]
V0.8.1 works, but after update to 0.9.0 and reload vscode, it doesn't seem to work anymore. Same for my colleagues.

![image](https://user-images.githubusercontent.com/22798719/103301562-ab8af280-49cf-11eb-8355-0fc16eef7fe6.png)
![image](https://user-images.githubusercontent.com/22798719/103301591-b9407800-49cf-11eb-94ac-5f68a5887d12.png)

**Comment by tomoyukim** [comment]
@KLIII Thank you very much for your report and so sorry for your inconvenience. I published quick fix for this bug with v0.9.2.

**Comment by KLIII** [comment]
Thank you very much for the quick response! Wow, this version is so much better at least with syntax support of class diagrams, color choices of the default style, and preview refreshing!

The only thing that seems to be removed is the support of other theme choices (forest/dark), but with the new default theme, perhaps I don't need other themes anymore :)
