### ISSUE TITLE
ER Diagram can't parse attributes

### ISSUE THREAD

**Issue by tarzasai** [tomoyukim/vscode-mermaid-editor#34]
Version 0.10.0

Try with a sample from [the docs](https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram), like this:
```
erDiagram
    CAR ||--o{ NAMED-DRIVER : allows
    CAR {
        string registrationNumber
        string make
        string model
    }
    PERSON ||--o{ NAMED-DRIVER : is
    PERSON {
        string firstName
        string lastName
        int age
    }
```

It doesn't show the diagram, but if I save the file I get this in terminal:
```
[DigagramParseError]
Parse error on line 3:
...R : allows
    CAR (
        string re
----------------------^
Expecting ':', 'ZERO_OR_ONE', 'ZERO_OR_MORE', 'ONE_OR_MORE', 'ONLY_ONE', got '('
```

(Yes, there's a typo in the exception name)

**Comment by tomoyukim** [comment]
Thank you for your report! I could reproduce and fix it by upgrading mermaid.js to latest. Please check it with mermaid-editor 0.10.1.
