### ISSUE TITLE
Text overflows box in svg and png

### ISSUE THREAD

**Issue by rkristelijn** [tomoyukim/vscode-mermaid-editor#4]
When generating the image from the mmd file, the svg is oversize and in both png and svg the text overflows the boxes in the themes default and natural

**Comment by l-Marty-l** [comment]
<img width="409" alt="Screenshot 2019-08-22 at 16 32 36" src="https://user-images.githubusercontent.com/24259245/63523675-d8d1b180-c4fa-11e9-80a8-ee8fcadb94a5.png">

Text even overflows my boxes in preview mode, but it seems to happen on all extensions that do render mermaid. I'm on macOS. Any help appreciated.

**Comment by tomoyukim** [comment]
Yes. Unfortunately, it's a behavior of `mermaid.js` itself. So, I believe the lib will update and improve it in the future. Thank you!
