### ISSUE TITLE
Generated pictures from diagrams cut off

### ISSUE THREAD

**Issue by anselmringleben** [tomoyukim/vscode-mermaid-editor#40]
Not sure what changed exactly but suddenly the plugin is producing cut off images of diagrams as can be seen below. Without a change this was working ~2 weeks back.

Test .mmd file content (which rendered correctly in preview)
`
sequenceDiagram
%% @backgroundColor{white}
%% @outputScale{2.5}
    participant br as Browser
    participant fr as frontend
    participant ap as api
    participant ps as PostgreSQL
    participant pr as Prometheus
    participant ot as OpenTracing
    br->>fr: access Website
    activate fr
    fr-->>br: render Website
    fr->>ap: REST calls
    activate ap
    ap->>ps: query/update data
    activate ps
    ps-->>ap: return result
    deactivate ps
    opt In case of changed data
      ap-->>fr: update
      ap-xpr: dispatch logs
      ap-xot: dispatch tracing
      deactivate ap
    end
    fr-->>br: render update
    deactivate fr
`

generates this cut off picture:
![test](https://user-images.githubusercontent.com/10085281/114580869-85881600-9c7f-11eb-9fc7-36bda5beb315.png)

Version:
* VSCode: 1.55.1
* vscode-mermaid-editor: 0.10.1

**Comment by tomoyukim** [comment]
Thank you for your reporitng. This was fixed in v0.11.0, please check it out!
