### ISSUE TITLE
Direction in subgraphs

### ISSUE THREAD

**Issue by rcerny** [tomoyukim/vscode-mermaid-editor#47]
**Describe the bug**
Direction in subgraphs is not working.
It actually not a bug, but a reference to an older version of mermaid (8.9.2), where this feature is not supported. From version 8.10.2 the feature is supported.

**To Reproduce**
flowchart LR
  subgraph TOP
    direction TB
    subgraph B1
        direction RL
        i1 -->f1
    end
    subgraph B2
        direction BT
        i2 -->f2
    end
  end
  A --> TOP --> B
  B1 --> B2

**Comment by Illyrix** [comment]
the vscode-mermaid-editor has to update mermaid to the latest release to solve this problem [#2082](https://github.com/mermaid-js/mermaid/pull/2082)

**Comment by tomoyukim** [comment]
Thank you for your support! I released version 0.11.2 containing the latest mermaid-js at https://github.com/tomoyukim/vscode-mermaid-editor/releases/tag/v0.11.2
