### ISSUE TITLE
Text is not visible when using a VSCode dark theme

### ISSUE THREAD

**Issue by juancri** [tomoyukim/vscode-mermaid-editor#5]
When a dark theme is set for VSCode, the default text color for the mermaid preview is not visible. 

Example

```
sequenceDiagram

    participant Test1;
    participant Test2;

    loop: comment
        Note over Test1: This is a test
    end
```

![screenshot8](https://user-images.githubusercontent.com/1131070/66005420-4230d280-e460-11e9-8407-a82f3a3a8eae.png)

It looks like a simple solution would be to explicitly set the default background color for the preview.

PS: I see ```mermaid-editor.preview.backgroundColor``` can be set. May be the default should be white.

**Comment by tomoyukim** [comment]
Thank you for your good advise! I updated default background color to 'white' in v0.4.3.
