### ISSUE TITLE
Generating image fails with permissions error when using GitHub Repositories extension

### ISSUE THREAD

**Issue by leighmcculloch** [tomoyukim/vscode-mermaid-editor#54]
**Describe the bug**
When opening a repository using GitHub Repositories plugin, where the code is not checked out to a repo, attempting to generate an image from a diagram results in this error:

```
Unable to write file '/leighmcculloch/diagrams/merging-shared-iteration-number-simple.svg' (Unknown (FileSystemError): Error: EROFS: read-only file system, mkdir '/leighmcculloch')
```

**To Reproduce**
1. Install GitHub Repositories: https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub
2. Install Markdown Editor: https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor
3. Create a diagram, save it as an .mmd file.
4. Run the command `Mermaid:Generate image`

**Expected behavior**
Image would be generated in some form.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - VSCode version: v1.60.2
 - Extension version: v0.11.4

**Additional context**
N/A

**Comment by tomoyukim** [comment]
It seems the target directory has read-only permission. Could you try to change the `outputPath` config with another directory that has write permission?
