### ISSUE TITLE
Copy image shortcut like Excalidraw extension

### ISSUE THREAD

**Issue by leighmcculloch** [tomoyukim/vscode-mermaid-editor#55]
It would be very convenient if the Mermaid Editor supported a copy shortcut which generate an image and copied it into the clipboard. For many workflows this is faster and more convenient than saving a file to disk then copying it or uploading it elsewhere.

A great example of how copying images can be more convenient is when drawing images in VSCode and then wanting to post them in GitHub issue/PR comments. Doing so with the extension as is requires saving the file somewhere, then uploading it to GitHub in the comment. However, if the extension supported copying the image directly to clipboard, the user could paste directly into a GitHub comment box and GitHub will upload the image from the clipboard into the comment.

The [Excalidraw extension](https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) is another diagram drawing extension for VSCode that offers this feature, and it makes getting images out of the extension very convenient. I use the workflow described above with it, and I think this extension would benefit from it.

**Comment by leighmcculloch** [comment]
Here's an example of the workflow in the Escalidraw extension:

https://user-images.githubusercontent.com/351529/135026900-b6124357-6fe8-469c-aaca-858828ef19a9.mp4

**Comment by tomoyukim** [comment]
@leighmcculloch Thank you for your suggestion and for waiting. I released v0.17.1 for supporting this clipboard shortcut. For the details, refer to README, please.

**Comment by leighmcculloch** [comment]
Thanks!!!!
