### ISSUE TITLE
mermaid-editor.preview.defaultMermaidConfig restart issue

### ISSUE THREAD

**Issue by ramchalluri** [tomoyukim/vscode-mermaid-editor#56]
**Describe the bug**
It looks like, the plugin ignores the "mermaid-editor.preview.defaultMermaidConfig" setting when restarted. We need to make a small change to the settings file to reload the setting value. 

**To Reproduce**
1. Go to 'settings.json'
2. Scroll down to 'mermaid-editor.preview.defaultMermaidConfig'
3. Set the value to point to a mermaid-js.json file. `{ "theme": "forest"}`
4. Check if its working fine, it should apply the `forest` theme. 
5. Restart vscode. 
6. Check if the mmd is still rendering with `forest` theme. it won't. 
7. make a small change to the settings file, save it and change it back to what it should be 
8. Check if its working fine, it should apply the `forest` theme. 

**Expected behavior**
To persist the config changes. 

**Screenshots**
let me know if you want me to record this. 

**Desktop (please complete the following information):**
 - OS: [e.g. `Windows 10`]
 - VSCode `1.63.0`
 - Extension version: `v0.11.4`

**Additional context**

**Comment by tomoyukim** [comment]
Thank you very much for reporting it. I fixed the bug on v0.11.5. Check it out, please.

**Comment by ramchalluri** [comment]
Hi, 
Thank you for addressing it soo quickly. I have tested the new version and yes its fixed, wonderful.
