### ISSUE TITLE
Upgrade mermaid version to 8.13.9

### ISSUE THREAD

**Issue by ebjornset** [tomoyukim/vscode-mermaid-editor#58]
Hi,

I see that dependabot has [an open PR](https://github.com/tomoyukim/vscode-mermaid-editor/pull/57) to upgrade Mermaid to 8.13.8. How far away is the next version with this update? My diagrams renders ok in Mermaid Live (currently at v version 8.13.8), but vscode-mermaid-editor only reports syntax errors.

**Comment by ebjornset** [comment]
Hi,

Mermaid released 8.13.9 with some minor improvements. Would it be possible to upgrade Mermaid to 8.13.9 in the near future?

**Comment by tomoyukim** [comment]
Sorry for my late update. I updated mermaid version to the latest.
