### ISSUE TITLE
Gitgraph doesn't render

### ISSUE THREAD

**Issue by dannief** [tomoyukim/vscode-mermaid-editor#63]
**Describe the bug**
The follow mermaid diagram code doesn't render i.e. just produces a white screen in the preview

```
gitGraph
  commit
  commit
  commit
```

```mermaid
gitGraph
  commit
  commit
  commit
```

**To Reproduce**
1.Install extension
2. Add file with .mmd extension
3. Add the above code to file
4. Select F1 and then `Mermaid: Preview diagram`
5. See bank preview window

**Expected behavior**
Expected git graph to be displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - VSCode version: 1.69.2
 - Extension version: v0.14.0

**Additional context**

**Comment by tomoyukim** [comment]
This is caused by the old mermaid version. I updated it to the latest in v0.15.0.
