### ISSUE TITLE
Mindmap graphs not working

### ISSUE THREAD

**Issue by chorca** [tomoyukim/vscode-mermaid-editor#69]
**Describe the bug**
Using Mindmaps does not appear to be working.
Copying and pasting the example from https://mermaid-js.github.io/mermaid/#/mindmap gives
```
[DigagramParseError]
undefined
```
in the output pane, and no graph is generated, instead a Mermaid error message "Syntax error in graph" is shown in the preview pane.

This same graph works properly at the Mermaid Live editor at https://mermaid.live/

**To Reproduce**
1. Open a new .mmd file
2. Paste in the example text from https://mermaid-js.github.io/mermaid/#/mindmap
3. Save file

**Expected behavior**
Graph is displayed properly as at https://mermaid.live/

**Screenshots**
![image](https://user-images.githubusercontent.com/1699703/200907268-ee48465e-ee7e-4762-9472-32053dedcb9d.png)

**Desktop:**
 - OS: Ubuntu 20.04.5
 - VSCode 1.73.0
 - Extension tomoyukim.vscode-mermaid-editor@0.17.1

**Comment by tomoyukim** [comment]
Thank you for your report! It seems this is an experimental feature and has not been included in mermaid.js itself so far. Let me consider how to support future updates including the mindmap from the mermaid.js project.

**Comment by KajiTetsushi** [comment]
@tomoyukim Could it be that `mermaid` is starting to get out of date? The Mermaid releases say that the mindmap syntax is available starting from [`v9.3.0`](https://github.com/mermaid-js/mermaid/releases/tag/v9.3.0). The current stable is, in fact, already in `v10.0.0`, which ships with syntaxes for even more kinds of diagrams, which I'm definitely interested to have.
