### ISSUE TITLE
Mermaid Version 8.4

### ISSUE THREAD

**Issue by J-Setzer** [tomoyukim/vscode-mermaid-editor#7]
Can you please support latest **mermaid version 8.4**. 

There is a new diagram type: **state diagrams**
https://mermaidjs.github.io/#/stateDiagram

Thank you very much!
Kind regards,
Jan

**Comment by tomoyukim** [comment]
Hello. Thank you for your great advise. I've published new version with mermaid version 8.4 with supporting font-awesome (thanks to @pngarland!)
