### ISSUE TITLE
Publish mermaid-editor on https://open-vsx.org/

### ISSUE THREAD

**Issue by arthurzenika** [tomoyukim/vscode-mermaid-editor#71]
**Describe the bug**
I'm using https://vscodium.com/ which in turn uses https://open-vsx.org/

Right now mermaid-editor isn't easily installable with that setup. Any chances of seeing this plugin in open-vsx ? Thanks in advance ! 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - VSCode version: VSCodium

**Comment by tomoyukim** [comment]
Hi @arthurzenika , thank you for the information. I never knew that before. I finally published the extension to ovsx too. Please check it on [mermaid-editor](https://open-vsx.org/extension/tomoyukim/vscode-mermaid-editor#mermaid-editor) on open-vsx.org!

**Comment by arthurzenika** [comment]
That's awesome ! Thanks @tomoyukim !
