### ISSUE TITLE
Are diagrams rendered fully offline without 3rd party services?

### ISSUE THREAD

**Issue by sadsimulation** [tomoyukim/vscode-mermaid-editor#74]
Hi,

I would like to use this extension at my place of work but I would rather not have sensitive information be uploaded to any external 3rd parties. Does this extension render all the diagrams locally or is the diagram rendered on some remote server and retrieved?

If the rendering is done fully local, you should definitely mention this feature in the readme, I can imagine many developers are facing restrictions on what external / cloud tools they're allowed to use.

Thank you!

**Comment by tomoyukim** [comment]
Yes, this extension doesn't use any external 3rd party services. This extension uses mermaid.js to render the diagram in WebView provided by VSCode. So, I think your code should not be sent to any remote server as long as not sent by mermaid.js itself. And mermaid.js doesn't as far as I know.

> If the rendering is done fully local, you should definitely mention this feature in the readme, I can imagine many developers are facing restrictions on what external / cloud tools they're allowed to use.

Thank you for your advice! I'll add such a description in the README.
