### ISSUE TITLE
Allow user to provide `mermaidPath`?

### ISSUE THREAD

**Issue by frisbee09** [tomoyukim/vscode-mermaid-editor#79]
I see from the `package.json` we are still using `9.4.0`.
Is there an easy way to decouple the deployment of the extension with the version of mermaid that comes with the extension? With how the extension functions currently, you'll need to release a new version every time the `mermaid` lot release something new.

For instance, using `v10` features is giving me syntax errors and I don't see an easy way for me to choose my mermaid version. I love the extension but this is a sure way to make sure it ends up out of date with `mermaid`.

**Comment by tomoyukim** [comment]
Thank you for your feedback. I also think it is a great idea. Let me consider adding it in the future release.

**Comment by philtrue-aa** [comment]
In the meantime, how about adding version 10? That way some of the new syntax is supported until this feature is added.

**Comment by tomoyukim** [comment]
Thank you for your patience. I published v0.19.1 with mermaid.js v10. Also, I included the feature to change the mermaid version referred to by the extension.

**Comment by philtrue-aa** [comment]
Nicely done! Kudos!
