### ISSUE TITLE
Preview for class diagram with namespaces doesn't work

### ISSUE THREAD

**Issue by DigitalAssasin** [tomoyukim/vscode-mermaid-editor#89]
**Describe the bug**
I try to define a class diagram as in the attached file.

This snippet works perfectly in mermaid's live editor. But the current version of the plugin displays an error:

Syntax error in graph
mermaid version 9.4.0

There are no errors in the terminal

**Comment by eddorre** [comment]
This is because namespace support was added in v10.2.0 as shown here: https://github.com/mermaid-js/mermaid/issues/4481#issuecomment-1588517540.

**Comment by tomoyukim** [comment]
Thank you for your report! I published v0.19.1 with the latest mermaid.js. Could you try it?

**Comment by DigitalAssasin** [comment]
Thanks a lot! The support of namespaces works like a charm in the latest version. I will close this issue.
