### ISSUE TITLE
Specify mermaid configuration/stylesheet

### ISSUE THREAD

**Issue by kammoh** [tomoyukim/vscode-mermaid-editor#9]
Is there a way to associate mermaid configuration and/or stylesheet with a mmd file for display or export?

**Comment by tomoyukim** [comment]
Thank you for your feedback. Let me confirm what you need. Do you want to manage the configuration with each mmd file independently?
Currently, it doesn't support full configuration for mermaid.js. Only theme or backgroundColor can be set. But applied theme or color can be reflected to exported image. If there's needs for full supporting the configuration, I'll consider to implement it in the future version.

**Comment by kammoh** [comment]
Yes, that would be great, thanks! I need access to the full configuration for each individual graph.

**Comment by erikreedstrom** [comment]
Is it possible to add configuration option for `themeCss`?

**Comment by tomoyukim** [comment]
Hello, I've published v0.6.0 with new attribute comment to associate individual mermaid.js config file with the `.mmd` file. I believe it's good answer for your requirement. For the way to use, please refer to [README](https://github.com/tomoyukim/vscode-mermaid-editor#attributes).
